name: Docker
# This workflow builds the conda-store-ui docker image for each
# pull request. This will ensure that no PR is breaking the docker
# image, which will be built and pushed to GHCR when a new release
# is cut.

on:
  pull_request:

jobs:
  build_docker_image:
    name: "Build Docker Image ğŸ› "
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository ğŸ›"
        uses: actions/checkout@v4

      - name: "Set up Docker Buildx ğŸ—"
        uses: docker/setup-buildx-action@v3

      - name: "Build image ğŸš€"
        uses: docker/build-push-action@v5
        with:
          context: .
          target: "prod"
          push: false
