name: Build Docker image

on:
  pull_request:

jobs:
  build_docker_image:
    name: "Build Docker Images ğŸ› "
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository ğŸ›"
        uses: actions/checkout@v4

      - name: "Set up Docker Buildx ğŸ—"
        uses: docker/setup-buildx-action@v3

      # - name: "Login to Docker Hub ğŸ³"
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_QUANSIGHT_USERNAME }}
      #     password: ${{ secrets.DOCKER_QUANSIGHT_PASSWORD }}

      - name: "Login to quay.io ğŸ³"
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_QUANSIGHT_USERNAME }}
          password: ${{ secrets.QUAY_QUANSIGHT_PASSWORD }}

      - name: "Build Docker image ğŸš€"
        uses: docker/build-push-action@v5
        with:
          context: .
          target: "prod"
          push: false
