name: build/deploy storybook
on:
  push:
    paths: ["story/**/*.stories.*"] # Trigger the action only when files change in the folders defined here
permissions:
  contents: write
jobs:
  builddeploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and Build ğŸ”§
        run: | # Install npm packages and build the Storybook files
          yarn
          yarn storybook:build
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static # The folder that the build-storybook script generates files.
          branch: gh-pages-storybook # The branch the action should deploy to.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs
          # token: ${{ secrets.GITHUB_TOKEN }}
